### ISSUE TITLE
Support mixed indexing (lists and slices)

### ISSUE THREAD

**Issue by freeman-lab** [bolt-project/bolt#75]
We should be able to use mixed list and slice indexing, for example,

```python
barray = bolt.array(arange(24).reshape(2,3,4), context=sc)
barray[:,[0,2],:]
```
which currently throws a `NotImplementedError`

for reference, it should return exactly the same thing as numpy, e.g.

```python
a = barray[:,[0,2],:].toarray()
b = barray.toarray()[:,[0,2],:]
assert allclose(a, b)
```

thanks to @boazmohar for flagging, cc @jwittenbach

**Comment by shoyer** [comment]
Beware -- you will run into some weird edge cases when you attempt to combine list and slice indexing: https://github.com/numpy/numpy/pull/6256/files

**Comment by freeman-lab** [comment]
Thanks @shoyer , I think we already have =) @jwittenbach is prepping a PR now, but I think we landed on supporting, for now, a fairly narrow form of mixed indexing.
