### ISSUE TITLE
Fail early on out of bounds indexing

### ISSUE THREAD

**Issue by freeman-lab** [bolt-project/bolt#76]
Currently, indexing out of bounds along an axis only throws an error upon conversion to a local array, e.g. with the array

```python
barray = bolt.array(arange(24).reshape(2,3,4), context=sc)
```

this works
```python
barray[0:1,:,:].toarray().shape
>> (1, 3, 4)
barray[1:2,:,:].toarray().shape
>> (1, 3, 4)
```
but this fails
```python
barray[2:3,:,:].shape
>> (1, 3, 4)
barray[2:3,:,:].toarray().shape
>> ValueError: total size of new array must be unchanged
```

the initial indexing appears to succeed and shows an array of shape `(1,3,4)` but after `toarray()` there is an error because the actual shape and the inferred shape differs. By comparison, in numpy, it results in an empty array

```python
barray.toarray()[2:3,:,:].shape
>> (0, 3, 4)
```

In this case, I think that unlike `numpy` we should throw an error immediately upon out-of-bounds indexing.

Thanks for flagging @boazmohar, cc @jwittenbach

**Comment by jwittenbach** [comment]
Closed by #77
